export const GET_TWITCH_DATA = 'GET_TWITCH_DATA';
export const TWITCH_DATA_RESULTS = 'TWITCH_DATA_RESULTS';
export const TWITCH_DATA_ERROR = 'TWITCH_DATA_ERROR';
export const UPDATE_FILTER = 'UPDATE_FILTER';
